server:
  port: 8080
  servlet:
    context-path: /identity
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "OpEa6c/FAqnusCQqixDPxtaNHLZ5sExi6M+2aDAGW+gMUe/yRSqN9mhmaRWb+sJ2"
  valid-duration: 3600 #phút
  refreshable-duration: 360000 # phút

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: DEBUG
    com.fasterxml.jackson.databind: DEBUG

